### ISSUE TITLE
Holding Shift hides items

### ISSUE THREAD

**Issue by Okimo** [starforcraft/Universal-Grid#4]
When I hold Shift the items disappear from grid.

https://user-images.githubusercontent.com/12627805/141130266-b16e2b93-f61a-43e5-8aa1-442fa8db62e7.mp4

**Comment by starforcraft** [comment]
Update Universal Grid

**Comment by Okimo** [comment]
Forgot to mention:
Its recorded on latest available update:
universalgrid-1.16.5-0.123.jar

**Comment by starforcraft** [comment]
Hmm are you on server?

**Comment by Okimo** [comment]
Its Singleplayer world

**Comment by starforcraft** [comment]
Can you send your log?

**Comment by Okimo** [comment]
Unfor. not anymore.
Recently I had issue when any modpack would crash on world load. So I was trying to fix my launcher thinking its error of Java or something else. During that I accidentally deleted all my instances including one that had this issue going on :/

**Comment by starforcraft** [comment]
lol

**Comment by NightOps007** [comment]
MC-1.16.5
Forge-36.2.0
RS-1.9.16
RS_Addons-0.7.4
Universal_Grid-0.125

@starforcraft, I think you closed this issue too soon. I have the same same issue happening in my sp world. Though, I've found that disabling the 'prevent sorting while shift is down' option in RS's client configs for the grid is an okay work-around fix for this bug. Really like that feature of RS though and hope that universal grid can support it as well in the future.

Other than the disappearing items, I've also noticed wrong numbers appearing while shift-clicking in the normal RS crafting grid, after I've used the universal grid's crafting grid once after starting the game. Relogging clears this bug until the next time I use the universal grid.

Before:
![2021-12-23_23 51 13](https://user-images.githubusercontent.com/5381709/147331582-f8cbc363-499c-4cda-9f96-d806a49bff7f.png)
After shift-clicking a stack of iron ingots out of grid, while still holding down the shift key:
![2021-12-23_23 51 21](https://user-images.githubusercontent.com/5381709/147331611-66bc598a-d3a6-4b58-96cb-2a760854cd7a.png)
After releasing the shift key(there is no iron visible in the grid even if you scroll down):
![2021-12-23_23 51 25](https://user-images.githubusercontent.com/5381709/147331633-7a456280-70c4-4078-9cb4-46c92ec61f9a.png)
After shift-clicking the stack of iron back into the grid:
![2021-12-23_23 51 30](https://user-images.githubusercontent.com/5381709/147331652-fbf7a6e3-88e5-49cf-b83d-aea93506c2dc.png)

I've no idea why this happens. Other items bug out the same as well, so it's not just because I have my iron in compacting storage drawers. I didn't notice anything odd appearing in the game's log while this was happening, but I've included it anyways.
[latest.log](https://github.com/starforcraft/Universal-Grid/files/7773426/latest.log)
